---
- hosts: all
  become: true
  tasks:
    # Get the last modification time of the apt package cache
    - name: Get stat of last run apt
      stat:
        path: /var/cache/apt/pkgcache.bin
      register: apt_run

    # Check if apt update was run today
    - name: "Check if apt update actions are needed"
      debug:
        msg: "Skipping apt-update, etc. actions as apt update was run today"
      when: "'%Y-%m-%d' | strftime(apt_run.stat.mtime) in ansible_date_time.date"

    # Perform apt update and maintenance if it hasn't been run today
    - name: "Run apt update, full-upgrade, autoremove, and autoclean"
      apt:
        upgrade: full
        update_cache: yes
        autoremove: yes
        autoclean: yes
      when: "'%Y-%m-%d' | strftime(apt_run.stat.mtime) not in ansible_date_time.date"
